version: '3.8'
services:
  api:
    build: .
    container_name: cinemais-api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: cinemais-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
